const regex = {
  android: /\.(apk|aab|slim)$/i,
  babel: /(^\.babelrc$)|(^babel\.config\.json$)|(^\.babelrc\.js$)|(^\.babelrc\.json$)/i,
  astro: /\.astro$/i,
  css: /\.css$/i,
  docker: /\.docker(file|ignore)$/i,
  eslint: /(^\.eslintrc(\.(json5|yaml|toml))?$|eslint\.config\.(js|json)$|\.eslintignore)/i,
  git: /(^\.gitignore$)|(^\.gitmodules$)|(^\.gitattributes)/i,
  html: /\.html$/i,
  image: /\.(png|jpg|jpeg|gif|bmp|ico|webp)$/i,
  java: /\.java$/i,
  javascript: /\.js\.map$/i,
  jsconfig: /^jsconfig\.json$/i,
  license: /^(license|LICENSE|License)$/i,
  nix: /\.nix$/i,
  npm: /(^package\.json$)|(^package-lock\.json$)|(^\.npmrc$)/i,
  pandaconfig: /panda\.config\.(js|ts)$/i,
  postcssconfig: /(^\.postcssrc(\.(json5|yaml|toml))?$|postcss\.config\.(js|json)$)/i,
  prettier: /(^\.prettierrc(\.(json5|yaml|toml))?$|prettier\.config\.(js|json)$)/i,
  robots: /^robots\.txt$/i,
  scss: /\.scss$/i,
  tsconfig: /^tsconfig\.json$/i,
  tsx: /\.tsx$/i,
  typescript: /\.d\.ts$/i,
  webpack: /^webpack\.config\.js$/i,
  yaml: /\.(yaml|yml)$/i,
};

export default regex;